# Freeze the FastAPI backend into a standalone binary with PyInstaller.
#
# Run from the repo root, with the venv activated:
#   .\.venv\Scripts\Activate.ps1
#   .\scripts\build_backend_binary.ps1
#
# Output: dist\backend\nexam-backend\ (onedir bundle), which
# src-tauri\tauri.conf.json's bundle.resources maps into the packaged app.
#
# Deliberately a separate script from build_backend_binary.sh rather than one
# shared cross-platform script -- this keeps the macOS release path
# byte-identical. Collapsing both into one Python script is a reasonable
# follow-up once Windows has shipped once.

Set-Location (Join-Path $PSScriptRoot "..")

$version = (Get-Content "src-tauri\tauri.conf.json" -Raw | ConvertFrom-Json).version
Write-Output "Baking backend version $version"

$bakedVersionPath = "app\backend\_baked_version.py"
@"
# Generated by scripts/build_backend_binary.ps1 -- do not edit.
BAKED_VERSION = "$version"
"@ | Set-Content -Encoding utf8 $bakedVersionPath

try {
    pyinstaller --name nexam-backend --onedir --noconfirm `
        --distpath dist/backend --workpath build/backend --specpath build `
        --paths . `
        --hidden-import uvicorn.logging `
        --hidden-import uvicorn.lifespan.on `
        --hidden-import uvicorn.protocols.http.h11_impl `
        --hidden-import multipart `
        --hidden-import multipart.multipart `
        app/backend/bundle_entrypoint.py

    if ($LASTEXITCODE -ne 0) {
        throw "pyinstaller exited with code $LASTEXITCODE"
    }
} finally {
    Remove-Item -Force -ErrorAction SilentlyContinue $bakedVersionPath
}

Write-Output "Wrote dist\backend\nexam-backend\ (version $version)"
